
-- local lsp = require("lspconfig")
-- 
-- lsp.clojure_lsp.setup(require("lsp.languages.clojure").lsp)
-- lsp.dockerls.setup(require("lsp.languages.docker").lsp)
-- lsp.gopls.setup(require("lsp.languages.go").lsp)
-- lsp.jsonls.setup(require("lsp.languages.json").lsp)
-- lsp.pyright.setup(require("lsp.languages.python").lsp)
-- lsp.sumneko_lua.setup(require("lsp.languages.lua").lsp)
-- lsp.texlab.setup(require("lsp.languages.latex").lsp)
-- lsp.tsserver.setup(require("lsp.languages.typescript").lsp)
-- lsp.yamlls.setup(require("lsp.languages.yaml").lsp)
-- lsp.zeta_note.setup(require("lsp.languages.markdown").lsp)
