require("plugins_packer_style")
require("utils.core")
require("settings")

require("plugins_packer_style.gitsigns")
require("plugins_packer_style.icons")
require("plugins_packer_style.kind")
require("plugins_packer_style.bufferline")
require("plugins_packer_style.evil-lualine")
require("plugins_packer_style.treesitter")
require("plugins_packer_style.autopairs")
require("plugins_packer_style.neoscroll")

require("plugins_packer_style.cmp")
require("lsp")

require("plugins_packer_style.fugitive")
require("plugins_packer_style.dap")
require("plugins_packer_style.telescope")
require("plugins_packer_style.neorg")
require("plugins_packer_style.toggleterm")
require("plugins_packer_style.alpha")
require("plugins_packer_style.conjure")

require("plugins_packer_style.marks")
require("plugins_packer_style.winsep")
require("plugins_packer_style.leap")
require("plugins_packer_style.flit")
require("mappings")
require("statuscol")
