require("plugins")
require("utils.core")
require("settings")

require("plugins.gitsigns")
require("plugins.icons")
require("plugins.kind")
require("plugins.bufferline")
require("plugins.evil-lualine")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.cmdline")
require("plugins.neoscroll")

require("plugins.cmp")
require("plugins.lspconfig")
require("lsp.efm")

require("plugins.dap")
require("plugins.worktree")
require("plugins.telescope")
require("plugins.toggleterm")
require("plugins.alpha")

require("plugins.marks")
require("mappings")
