require("plugins")
require("utils.core")
require("settings")

require("plugins.gitsigns")
require("plugins.icons")
require("plugins.kind")
require("plugins.bufferline")
require("plugins.evil-lualine")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.neoscroll")

require("plugins.cmp")
require("lsp")

require("plugins.fugitive")
require("plugins.dap")
require("plugins.telescope")
require("plugins.neorg")
require("plugins.toggleterm")
require("plugins.alpha")
require("plugins.conjure")

require("plugins.marks")
require("plugins.winsep")
require("plugins.leap")
require("plugins.flit")
require("mappings")
require("statuscol")
